/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecole221.common.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EtudiantCreeAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1514181381366168963L;

  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EtudiantCreeAvroModel\",\"namespace\":\"com.ecole221.common.avro\",\"fields\":[{\"name\":\"etudiantId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"matricule\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"nom\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"prenom\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"dateNaissance\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"occurredAt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"email\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EtudiantCreeAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EtudiantCreeAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  public static BinaryMessageEncoder<EtudiantCreeAvroModel> getEncoder() { return ENCODER; }
  public static BinaryMessageDecoder<EtudiantCreeAvroModel> getDecoder() { return DECODER; }

  public static BinaryMessageDecoder<EtudiantCreeAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  public static EtudiantCreeAvroModel fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String etudiantId;
  private java.lang.String matricule;
  private java.lang.String nom;
  private java.lang.String prenom;
  private java.lang.String dateNaissance;
  private java.lang.String occurredAt;
  private java.lang.String email;

  public EtudiantCreeAvroModel() {}

  public EtudiantCreeAvroModel(java.lang.String etudiantId, java.lang.String matricule,
      java.lang.String nom, java.lang.String prenom, java.lang.String dateNaissance,
      java.lang.String occurredAt, java.lang.String email) {
    this.etudiantId = etudiantId;
    this.matricule = matricule;
    this.nom = nom;
    this.prenom = prenom;
    this.dateNaissance = dateNaissance;
    this.occurredAt = occurredAt;
    this.email = email;
  }

  @Override public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  @Override public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return etudiantId;
    case 1: return matricule;
    case 2: return nom;
    case 3: return prenom;
    case 4: return dateNaissance;
    case 5: return occurredAt;
    case 6: return email;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: etudiantId = value$ != null ? value$.toString() : null; break;
    case 1: matricule = value$ != null ? value$.toString() : null; break;
    case 2: nom = value$ != null ? value$.toString() : null; break;
    case 3: prenom = value$ != null ? value$.toString() : null; break;
    case 4: dateNaissance = value$ != null ? value$.toString() : null; break;
    case 5: occurredAt = value$ != null ? value$.toString() : null; break;
    case 6: email = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  public java.lang.String getEtudiantId() { return etudiantId; }
  public void setEtudiantId(java.lang.String value) { this.etudiantId = value; }
  public java.lang.String getMatricule() { return matricule; }
  public void setMatricule(java.lang.String value) { this.matricule = value; }
  public java.lang.String getNom() { return nom; }
  public void setNom(java.lang.String value) { this.nom = value; }
  public java.lang.String getPrenom() { return prenom; }
  public void setPrenom(java.lang.String value) { this.prenom = value; }
  public java.lang.String getDateNaissance() { return dateNaissance; }
  public void setDateNaissance(java.lang.String value) { this.dateNaissance = value; }
  public java.lang.String getOccurredAt() { return occurredAt; }
  public void setOccurredAt(java.lang.String value) { this.occurredAt = value; }
  public java.lang.String getEmail() { return email; }
  public void setEmail(java.lang.String value) { this.email = value; }

  public static com.ecole221.common.avro.EtudiantCreeAvroModel.Builder newBuilder() {
    return new com.ecole221.common.avro.EtudiantCreeAvroModel.Builder();
  }

  public static com.ecole221.common.avro.EtudiantCreeAvroModel.Builder newBuilder(
      com.ecole221.common.avro.EtudiantCreeAvroModel.Builder other) {
    return other == null ? new com.ecole221.common.avro.EtudiantCreeAvroModel.Builder()
        : new com.ecole221.common.avro.EtudiantCreeAvroModel.Builder(other);
  }

  public static com.ecole221.common.avro.EtudiantCreeAvroModel.Builder newBuilder(
      com.ecole221.common.avro.EtudiantCreeAvroModel other) {
    return other == null ? new com.ecole221.common.avro.EtudiantCreeAvroModel.Builder()
        : new com.ecole221.common.avro.EtudiantCreeAvroModel.Builder(other);
  }

  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EtudiantCreeAvroModel>
      implements org.apache.avro.data.RecordBuilder<EtudiantCreeAvroModel> {

    private java.lang.String etudiantId;
    private java.lang.String matricule;
    private java.lang.String nom;
    private java.lang.String prenom;
    private java.lang.String dateNaissance;
    private java.lang.String occurredAt;
    private java.lang.String email;

    private Builder() { super(SCHEMA$, MODEL$); }

    private Builder(com.ecole221.common.avro.EtudiantCreeAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.etudiantId)) { this.etudiantId = data().deepCopy(fields()[0].schema(), other.etudiantId); fieldSetFlags()[0] = other.fieldSetFlags()[0]; }
      if (isValidValue(fields()[1], other.matricule)) { this.matricule = data().deepCopy(fields()[1].schema(), other.matricule); fieldSetFlags()[1] = other.fieldSetFlags()[1]; }
      if (isValidValue(fields()[2], other.nom)) { this.nom = data().deepCopy(fields()[2].schema(), other.nom); fieldSetFlags()[2] = other.fieldSetFlags()[2]; }
      if (isValidValue(fields()[3], other.prenom)) { this.prenom = data().deepCopy(fields()[3].schema(), other.prenom); fieldSetFlags()[3] = other.fieldSetFlags()[3]; }
      if (isValidValue(fields()[4], other.dateNaissance)) { this.dateNaissance = data().deepCopy(fields()[4].schema(), other.dateNaissance); fieldSetFlags()[4] = other.fieldSetFlags()[4]; }
      if (isValidValue(fields()[5], other.occurredAt)) { this.occurredAt = data().deepCopy(fields()[5].schema(), other.occurredAt); fieldSetFlags()[5] = other.fieldSetFlags()[5]; }
      if (isValidValue(fields()[6], other.email)) { this.email = data().deepCopy(fields()[6].schema(), other.email); fieldSetFlags()[6] = other.fieldSetFlags()[6]; }
    }

    private Builder(com.ecole221.common.avro.EtudiantCreeAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.etudiantId)) { this.etudiantId = data().deepCopy(fields()[0].schema(), other.etudiantId); fieldSetFlags()[0] = true; }
      if (isValidValue(fields()[1], other.matricule)) { this.matricule = data().deepCopy(fields()[1].schema(), other.matricule); fieldSetFlags()[1] = true; }
      if (isValidValue(fields()[2], other.nom)) { this.nom = data().deepCopy(fields()[2].schema(), other.nom); fieldSetFlags()[2] = true; }
      if (isValidValue(fields()[3], other.prenom)) { this.prenom = data().deepCopy(fields()[3].schema(), other.prenom); fieldSetFlags()[3] = true; }
      if (isValidValue(fields()[4], other.dateNaissance)) { this.dateNaissance = data().deepCopy(fields()[4].schema(), other.dateNaissance); fieldSetFlags()[4] = true; }
      if (isValidValue(fields()[5], other.occurredAt)) { this.occurredAt = data().deepCopy(fields()[5].schema(), other.occurredAt); fieldSetFlags()[5] = true; }
      if (isValidValue(fields()[6], other.email)) { this.email = data().deepCopy(fields()[6].schema(), other.email); fieldSetFlags()[6] = true; }
    }

    public java.lang.String getEtudiantId() { return etudiantId; }
    public Builder setEtudiantId(java.lang.String value) { validate(fields()[0], value); this.etudiantId = value; fieldSetFlags()[0] = true; return this; }
    public boolean hasEtudiantId() { return fieldSetFlags()[0]; }
    public Builder clearEtudiantId() { etudiantId = null; fieldSetFlags()[0] = false; return this; }

    public java.lang.String getMatricule() { return matricule; }
    public Builder setMatricule(java.lang.String value) { validate(fields()[1], value); this.matricule = value; fieldSetFlags()[1] = true; return this; }
    public boolean hasMatricule() { return fieldSetFlags()[1]; }
    public Builder clearMatricule() { matricule = null; fieldSetFlags()[1] = false; return this; }

    public java.lang.String getNom() { return nom; }
    public Builder setNom(java.lang.String value) { validate(fields()[2], value); this.nom = value; fieldSetFlags()[2] = true; return this; }
    public boolean hasNom() { return fieldSetFlags()[2]; }
    public Builder clearNom() { nom = null; fieldSetFlags()[2] = false; return this; }

    public java.lang.String getPrenom() { return prenom; }
    public Builder setPrenom(java.lang.String value) { validate(fields()[3], value); this.prenom = value; fieldSetFlags()[3] = true; return this; }
    public boolean hasPrenom() { return fieldSetFlags()[3]; }
    public Builder clearPrenom() { prenom = null; fieldSetFlags()[3] = false; return this; }

    public java.lang.String getDateNaissance() { return dateNaissance; }
    public Builder setDateNaissance(java.lang.String value) { validate(fields()[4], value); this.dateNaissance = value; fieldSetFlags()[4] = true; return this; }
    public boolean hasDateNaissance() { return fieldSetFlags()[4]; }
    public Builder clearDateNaissance() { dateNaissance = null; fieldSetFlags()[4] = false; return this; }

    public java.lang.String getOccurredAt() { return occurredAt; }
    public Builder setOccurredAt(java.lang.String value) { validate(fields()[5], value); this.occurredAt = value; fieldSetFlags()[5] = true; return this; }
    public boolean hasOccurredAt() { return fieldSetFlags()[5]; }
    public Builder clearOccurredAt() { occurredAt = null; fieldSetFlags()[5] = false; return this; }

    public java.lang.String getEmail() { return email; }
    public Builder setEmail(java.lang.String value) { validate(fields()[6], value); this.email = value; fieldSetFlags()[6] = true; return this; }
    public boolean hasEmail() { return fieldSetFlags()[6]; }
    public Builder clearEmail() { email = null; fieldSetFlags()[6] = false; return this; }

    @Override
    @SuppressWarnings("unchecked")
    public EtudiantCreeAvroModel build() {
      try {
        EtudiantCreeAvroModel record = new EtudiantCreeAvroModel();
        record.etudiantId = fieldSetFlags()[0] ? this.etudiantId : (java.lang.String) defaultValue(fields()[0]);
        record.matricule = fieldSetFlags()[1] ? this.matricule : (java.lang.String) defaultValue(fields()[1]);
        record.nom = fieldSetFlags()[2] ? this.nom : (java.lang.String) defaultValue(fields()[2]);
        record.prenom = fieldSetFlags()[3] ? this.prenom : (java.lang.String) defaultValue(fields()[3]);
        record.dateNaissance = fieldSetFlags()[4] ? this.dateNaissance : (java.lang.String) defaultValue(fields()[4]);
        record.occurredAt = fieldSetFlags()[5] ? this.occurredAt : (java.lang.String) defaultValue(fields()[5]);
        record.email = fieldSetFlags()[6] ? this.email : (java.lang.String) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EtudiantCreeAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<EtudiantCreeAvroModel>) MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EtudiantCreeAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<EtudiantCreeAvroModel>) MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
    out.writeString(this.etudiantId);
    out.writeString(this.matricule);
    out.writeString(this.nom);
    out.writeString(this.prenom);
    out.writeString(this.dateNaissance);
    out.writeString(this.occurredAt);
    out.writeString(this.email);
  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.etudiantId = in.readString();
      this.matricule = in.readString();
      this.nom = in.readString();
      this.prenom = in.readString();
      this.dateNaissance = in.readString();
      this.occurredAt = in.readString();
      this.email = in.readString();
    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0: this.etudiantId = in.readString(); break;
        case 1: this.matricule = in.readString(); break;
        case 2: this.nom = in.readString(); break;
        case 3: this.prenom = in.readString(); break;
        case 4: this.dateNaissance = in.readString(); break;
        case 5: this.occurredAt = in.readString(); break;
        case 6: this.email = in.readString(); break;
        default: throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (etudiantId == null ? 0 : etudiantId.hashCode());
    result = 31 * result + (matricule == null ? 0 : matricule.hashCode());
    result = 31 * result + (nom == null ? 0 : nom.hashCode());
    result = 31 * result + (prenom == null ? 0 : prenom.hashCode());
    result = 31 * result + (dateNaissance == null ? 0 : dateNaissance.hashCode());
    result = 31 * result + (occurredAt == null ? 0 : occurredAt.hashCode());
    result = 31 * result + (email == null ? 0 : email.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (!(o instanceof EtudiantCreeAvroModel)) return false;
    EtudiantCreeAvroModel other = (EtudiantCreeAvroModel) o;
    return java.util.Objects.equals(this.etudiantId, other.etudiantId)
        && java.util.Objects.equals(this.matricule, other.matricule)
        && java.util.Objects.equals(this.nom, other.nom)
        && java.util.Objects.equals(this.prenom, other.prenom)
        && java.util.Objects.equals(this.dateNaissance, other.dateNaissance)
        && java.util.Objects.equals(this.occurredAt, other.occurredAt)
        && java.util.Objects.equals(this.email, other.email);
  }
}
