/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecole221.common.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class InscriptionTransfereAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7690879406613036953L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InscriptionTransfereAvroModel\",\"namespace\":\"com.ecole221.common.avro\",\"fields\":[{\"name\":\"inscriptionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"etudiantId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"nouvelleClasseId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"codeAnnee\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"fraisInscription\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"mensualite\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"autresFrais\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"moisAcademiques\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"[]\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InscriptionTransfereAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InscriptionTransfereAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<InscriptionTransfereAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<InscriptionTransfereAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<InscriptionTransfereAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this InscriptionTransfereAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a InscriptionTransfereAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a InscriptionTransfereAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static InscriptionTransfereAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String inscriptionId;
  private java.lang.String etudiantId;
  private java.lang.String nouvelleClasseId;
  private java.lang.String codeAnnee;
  private java.lang.String fraisInscription;
  private java.lang.String mensualite;
  private java.lang.String autresFrais;
  private java.lang.String moisAcademiques;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InscriptionTransfereAvroModel() {}

  /**
   * All-args constructor.
   * @param inscriptionId The new value for inscriptionId
   * @param etudiantId The new value for etudiantId
   * @param nouvelleClasseId The new value for nouvelleClasseId
   * @param codeAnnee The new value for codeAnnee
   * @param fraisInscription The new value for fraisInscription
   * @param mensualite The new value for mensualite
   * @param autresFrais The new value for autresFrais
   * @param moisAcademiques The new value for moisAcademiques
   */
  public InscriptionTransfereAvroModel(java.lang.String inscriptionId, java.lang.String etudiantId, java.lang.String nouvelleClasseId, java.lang.String codeAnnee, java.lang.String fraisInscription, java.lang.String mensualite, java.lang.String autresFrais, java.lang.String moisAcademiques) {
    this.inscriptionId = inscriptionId;
    this.etudiantId = etudiantId;
    this.nouvelleClasseId = nouvelleClasseId;
    this.codeAnnee = codeAnnee;
    this.fraisInscription = fraisInscription;
    this.mensualite = mensualite;
    this.autresFrais = autresFrais;
    this.moisAcademiques = moisAcademiques;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return inscriptionId;
    case 1: return etudiantId;
    case 2: return nouvelleClasseId;
    case 3: return codeAnnee;
    case 4: return fraisInscription;
    case 5: return mensualite;
    case 6: return autresFrais;
    case 7: return moisAcademiques;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: inscriptionId = value$ != null ? value$.toString() : null; break;
    case 1: etudiantId = value$ != null ? value$.toString() : null; break;
    case 2: nouvelleClasseId = value$ != null ? value$.toString() : null; break;
    case 3: codeAnnee = value$ != null ? value$.toString() : null; break;
    case 4: fraisInscription = value$ != null ? value$.toString() : null; break;
    case 5: mensualite = value$ != null ? value$.toString() : null; break;
    case 6: autresFrais = value$ != null ? value$.toString() : null; break;
    case 7: moisAcademiques = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'inscriptionId' field.
   * @return The value of the 'inscriptionId' field.
   */
  public java.lang.String getInscriptionId() {
    return inscriptionId;
  }


  /**
   * Sets the value of the 'inscriptionId' field.
   * @param value the value to set.
   */
  public void setInscriptionId(java.lang.String value) {
    this.inscriptionId = value;
  }

  /**
   * Gets the value of the 'etudiantId' field.
   * @return The value of the 'etudiantId' field.
   */
  public java.lang.String getEtudiantId() {
    return etudiantId;
  }


  /**
   * Sets the value of the 'etudiantId' field.
   * @param value the value to set.
   */
  public void setEtudiantId(java.lang.String value) {
    this.etudiantId = value;
  }

  /**
   * Gets the value of the 'nouvelleClasseId' field.
   * @return The value of the 'nouvelleClasseId' field.
   */
  public java.lang.String getNouvelleClasseId() {
    return nouvelleClasseId;
  }


  /**
   * Sets the value of the 'nouvelleClasseId' field.
   * @param value the value to set.
   */
  public void setNouvelleClasseId(java.lang.String value) {
    this.nouvelleClasseId = value;
  }

  /**
   * Gets the value of the 'codeAnnee' field.
   * @return The value of the 'codeAnnee' field.
   */
  public java.lang.String getCodeAnnee() {
    return codeAnnee;
  }


  /**
   * Sets the value of the 'codeAnnee' field.
   * @param value the value to set.
   */
  public void setCodeAnnee(java.lang.String value) {
    this.codeAnnee = value;
  }

  /**
   * Gets the value of the 'fraisInscription' field.
   * @return The value of the 'fraisInscription' field.
   */
  public java.lang.String getFraisInscription() {
    return fraisInscription;
  }


  /**
   * Sets the value of the 'fraisInscription' field.
   * @param value the value to set.
   */
  public void setFraisInscription(java.lang.String value) {
    this.fraisInscription = value;
  }

  /**
   * Gets the value of the 'mensualite' field.
   * @return The value of the 'mensualite' field.
   */
  public java.lang.String getMensualite() {
    return mensualite;
  }


  /**
   * Sets the value of the 'mensualite' field.
   * @param value the value to set.
   */
  public void setMensualite(java.lang.String value) {
    this.mensualite = value;
  }

  /**
   * Gets the value of the 'autresFrais' field.
   * @return The value of the 'autresFrais' field.
   */
  public java.lang.String getAutresFrais() {
    return autresFrais;
  }


  /**
   * Sets the value of the 'autresFrais' field.
   * @param value the value to set.
   */
  public void setAutresFrais(java.lang.String value) {
    this.autresFrais = value;
  }

  /**
   * Gets the value of the 'moisAcademiques' field.
   * @return The value of the 'moisAcademiques' field.
   */
  public java.lang.String getMoisAcademiques() {
    return moisAcademiques;
  }


  /**
   * Sets the value of the 'moisAcademiques' field.
   * @param value the value to set.
   */
  public void setMoisAcademiques(java.lang.String value) {
    this.moisAcademiques = value;
  }

  /**
   * Creates a new InscriptionTransfereAvroModel RecordBuilder.
   * @return A new InscriptionTransfereAvroModel RecordBuilder
   */
  public static com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder newBuilder() {
    return new com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder();
  }

  /**
   * Creates a new InscriptionTransfereAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InscriptionTransfereAvroModel RecordBuilder
   */
  public static com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder newBuilder(com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder other) {
    if (other == null) {
      return new com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder();
    } else {
      return new com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new InscriptionTransfereAvroModel RecordBuilder by copying an existing InscriptionTransfereAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new InscriptionTransfereAvroModel RecordBuilder
   */
  public static com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder newBuilder(com.ecole221.common.avro.InscriptionTransfereAvroModel other) {
    if (other == null) {
      return new com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder();
    } else {
      return new com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for InscriptionTransfereAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InscriptionTransfereAvroModel>
    implements org.apache.avro.data.RecordBuilder<InscriptionTransfereAvroModel> {

    private java.lang.String inscriptionId;
    private java.lang.String etudiantId;
    private java.lang.String nouvelleClasseId;
    private java.lang.String codeAnnee;
    private java.lang.String fraisInscription;
    private java.lang.String mensualite;
    private java.lang.String autresFrais;
    private java.lang.String moisAcademiques;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.inscriptionId)) {
        this.inscriptionId = data().deepCopy(fields()[0].schema(), other.inscriptionId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.etudiantId)) {
        this.etudiantId = data().deepCopy(fields()[1].schema(), other.etudiantId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.nouvelleClasseId)) {
        this.nouvelleClasseId = data().deepCopy(fields()[2].schema(), other.nouvelleClasseId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.codeAnnee)) {
        this.codeAnnee = data().deepCopy(fields()[3].schema(), other.codeAnnee);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.fraisInscription)) {
        this.fraisInscription = data().deepCopy(fields()[4].schema(), other.fraisInscription);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.mensualite)) {
        this.mensualite = data().deepCopy(fields()[5].schema(), other.mensualite);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.autresFrais)) {
        this.autresFrais = data().deepCopy(fields()[6].schema(), other.autresFrais);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.moisAcademiques)) {
        this.moisAcademiques = data().deepCopy(fields()[7].schema(), other.moisAcademiques);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing InscriptionTransfereAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ecole221.common.avro.InscriptionTransfereAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.inscriptionId)) {
        this.inscriptionId = data().deepCopy(fields()[0].schema(), other.inscriptionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.etudiantId)) {
        this.etudiantId = data().deepCopy(fields()[1].schema(), other.etudiantId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.nouvelleClasseId)) {
        this.nouvelleClasseId = data().deepCopy(fields()[2].schema(), other.nouvelleClasseId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.codeAnnee)) {
        this.codeAnnee = data().deepCopy(fields()[3].schema(), other.codeAnnee);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.fraisInscription)) {
        this.fraisInscription = data().deepCopy(fields()[4].schema(), other.fraisInscription);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.mensualite)) {
        this.mensualite = data().deepCopy(fields()[5].schema(), other.mensualite);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.autresFrais)) {
        this.autresFrais = data().deepCopy(fields()[6].schema(), other.autresFrais);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.moisAcademiques)) {
        this.moisAcademiques = data().deepCopy(fields()[7].schema(), other.moisAcademiques);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'inscriptionId' field.
      * @return The value.
      */
    public java.lang.String getInscriptionId() {
      return inscriptionId;
    }


    /**
      * Sets the value of the 'inscriptionId' field.
      * @param value The value of 'inscriptionId'.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder setInscriptionId(java.lang.String value) {
      validate(fields()[0], value);
      this.inscriptionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'inscriptionId' field has been set.
      * @return True if the 'inscriptionId' field has been set, false otherwise.
      */
    public boolean hasInscriptionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'inscriptionId' field.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder clearInscriptionId() {
      inscriptionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'etudiantId' field.
      * @return The value.
      */
    public java.lang.String getEtudiantId() {
      return etudiantId;
    }


    /**
      * Sets the value of the 'etudiantId' field.
      * @param value The value of 'etudiantId'.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder setEtudiantId(java.lang.String value) {
      validate(fields()[1], value);
      this.etudiantId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'etudiantId' field has been set.
      * @return True if the 'etudiantId' field has been set, false otherwise.
      */
    public boolean hasEtudiantId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'etudiantId' field.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder clearEtudiantId() {
      etudiantId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'nouvelleClasseId' field.
      * @return The value.
      */
    public java.lang.String getNouvelleClasseId() {
      return nouvelleClasseId;
    }


    /**
      * Sets the value of the 'nouvelleClasseId' field.
      * @param value The value of 'nouvelleClasseId'.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder setNouvelleClasseId(java.lang.String value) {
      validate(fields()[2], value);
      this.nouvelleClasseId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'nouvelleClasseId' field has been set.
      * @return True if the 'nouvelleClasseId' field has been set, false otherwise.
      */
    public boolean hasNouvelleClasseId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'nouvelleClasseId' field.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder clearNouvelleClasseId() {
      nouvelleClasseId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'codeAnnee' field.
      * @return The value.
      */
    public java.lang.String getCodeAnnee() {
      return codeAnnee;
    }


    /**
      * Sets the value of the 'codeAnnee' field.
      * @param value The value of 'codeAnnee'.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder setCodeAnnee(java.lang.String value) {
      validate(fields()[3], value);
      this.codeAnnee = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'codeAnnee' field has been set.
      * @return True if the 'codeAnnee' field has been set, false otherwise.
      */
    public boolean hasCodeAnnee() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'codeAnnee' field.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder clearCodeAnnee() {
      codeAnnee = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'fraisInscription' field.
      * @return The value.
      */
    public java.lang.String getFraisInscription() {
      return fraisInscription;
    }


    /**
      * Sets the value of the 'fraisInscription' field.
      * @param value The value of 'fraisInscription'.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder setFraisInscription(java.lang.String value) {
      validate(fields()[4], value);
      this.fraisInscription = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'fraisInscription' field has been set.
      * @return True if the 'fraisInscription' field has been set, false otherwise.
      */
    public boolean hasFraisInscription() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'fraisInscription' field.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder clearFraisInscription() {
      fraisInscription = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'mensualite' field.
      * @return The value.
      */
    public java.lang.String getMensualite() {
      return mensualite;
    }


    /**
      * Sets the value of the 'mensualite' field.
      * @param value The value of 'mensualite'.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder setMensualite(java.lang.String value) {
      validate(fields()[5], value);
      this.mensualite = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'mensualite' field has been set.
      * @return True if the 'mensualite' field has been set, false otherwise.
      */
    public boolean hasMensualite() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'mensualite' field.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder clearMensualite() {
      mensualite = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'autresFrais' field.
      * @return The value.
      */
    public java.lang.String getAutresFrais() {
      return autresFrais;
    }


    /**
      * Sets the value of the 'autresFrais' field.
      * @param value The value of 'autresFrais'.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder setAutresFrais(java.lang.String value) {
      validate(fields()[6], value);
      this.autresFrais = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'autresFrais' field has been set.
      * @return True if the 'autresFrais' field has been set, false otherwise.
      */
    public boolean hasAutresFrais() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'autresFrais' field.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder clearAutresFrais() {
      autresFrais = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'moisAcademiques' field.
      * @return The value.
      */
    public java.lang.String getMoisAcademiques() {
      return moisAcademiques;
    }


    /**
      * Sets the value of the 'moisAcademiques' field.
      * @param value The value of 'moisAcademiques'.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder setMoisAcademiques(java.lang.String value) {
      validate(fields()[7], value);
      this.moisAcademiques = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'moisAcademiques' field has been set.
      * @return True if the 'moisAcademiques' field has been set, false otherwise.
      */
    public boolean hasMoisAcademiques() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'moisAcademiques' field.
      * @return This builder.
      */
    public com.ecole221.common.avro.InscriptionTransfereAvroModel.Builder clearMoisAcademiques() {
      moisAcademiques = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InscriptionTransfereAvroModel build() {
      try {
        InscriptionTransfereAvroModel record = new InscriptionTransfereAvroModel();
        record.inscriptionId = fieldSetFlags()[0] ? this.inscriptionId : (java.lang.String) defaultValue(fields()[0]);
        record.etudiantId = fieldSetFlags()[1] ? this.etudiantId : (java.lang.String) defaultValue(fields()[1]);
        record.nouvelleClasseId = fieldSetFlags()[2] ? this.nouvelleClasseId : (java.lang.String) defaultValue(fields()[2]);
        record.codeAnnee = fieldSetFlags()[3] ? this.codeAnnee : (java.lang.String) defaultValue(fields()[3]);
        record.fraisInscription = fieldSetFlags()[4] ? this.fraisInscription : (java.lang.String) defaultValue(fields()[4]);
        record.mensualite = fieldSetFlags()[5] ? this.mensualite : (java.lang.String) defaultValue(fields()[5]);
        record.autresFrais = fieldSetFlags()[6] ? this.autresFrais : (java.lang.String) defaultValue(fields()[6]);
        record.moisAcademiques = fieldSetFlags()[7] ? this.moisAcademiques : (java.lang.String) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InscriptionTransfereAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<InscriptionTransfereAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InscriptionTransfereAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<InscriptionTransfereAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.inscriptionId);

    out.writeString(this.etudiantId);

    out.writeString(this.nouvelleClasseId);

    out.writeString(this.codeAnnee);

    out.writeString(this.fraisInscription);

    out.writeString(this.mensualite);

    out.writeString(this.autresFrais);

    out.writeString(this.moisAcademiques);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.inscriptionId = in.readString();

      this.etudiantId = in.readString();

      this.nouvelleClasseId = in.readString();

      this.codeAnnee = in.readString();

      this.fraisInscription = in.readString();

      this.mensualite = in.readString();

      this.autresFrais = in.readString();

      this.moisAcademiques = in.readString();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.inscriptionId = in.readString();
          break;

        case 1:
          this.etudiantId = in.readString();
          break;

        case 2:
          this.nouvelleClasseId = in.readString();
          break;

        case 3:
          this.codeAnnee = in.readString();
          break;

        case 4:
          this.fraisInscription = in.readString();
          break;

        case 5:
          this.mensualite = in.readString();
          break;

        case 6:
          this.autresFrais = in.readString();
          break;

        case 7:
          this.moisAcademiques = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (inscriptionId == null ? 0 : inscriptionId.hashCode());
    result = 31 * result + (etudiantId == null ? 0 : etudiantId.hashCode());
    result = 31 * result + (nouvelleClasseId == null ? 0 : nouvelleClasseId.hashCode());
    result = 31 * result + (codeAnnee == null ? 0 : codeAnnee.hashCode());
    result = 31 * result + (fraisInscription == null ? 0 : fraisInscription.hashCode());
    result = 31 * result + (mensualite == null ? 0 : mensualite.hashCode());
    result = 31 * result + (autresFrais == null ? 0 : autresFrais.hashCode());
    result = 31 * result + (moisAcademiques == null ? 0 : moisAcademiques.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof InscriptionTransfereAvroModel)) {
      return false;
    }
    InscriptionTransfereAvroModel other = (InscriptionTransfereAvroModel) o;
    if (!java.util.Objects.equals(this.inscriptionId, other.inscriptionId)) {
      return false;
    }
    if (!java.util.Objects.equals(this.etudiantId, other.etudiantId)) {
      return false;
    }
    if (!java.util.Objects.equals(this.nouvelleClasseId, other.nouvelleClasseId)) {
      return false;
    }
    if (!java.util.Objects.equals(this.codeAnnee, other.codeAnnee)) {
      return false;
    }
    if (!java.util.Objects.equals(this.fraisInscription, other.fraisInscription)) {
      return false;
    }
    if (!java.util.Objects.equals(this.mensualite, other.mensualite)) {
      return false;
    }
    if (!java.util.Objects.equals(this.autresFrais, other.autresFrais)) {
      return false;
    }
    if (!java.util.Objects.equals(this.moisAcademiques, other.moisAcademiques)) {
      return false;
    }
    return true;
  }
}










