spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: school-service

  profiles:
    active: mysql,dev

  # WSO2 API Gateway — validation JWT
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8180/realms/scolarite/protocol/openid-connect/certs
          issuer-uri: http://keycloak:8180/realms/scolarite

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8889/school-service
    username: root
    password: root
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 3000
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show_sql: true

server:
  port: 8094
  tomcat:
    threads:
      max: 400
      min-spare: 40
    accept-count: 400
    connection-timeout: 5s
